# Generated by Django 3.2.7 on 2021-09-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('desription', models.TextField()),
                ('slug', models.SlugField(max_length=25)),
            ],
        ),
    ]
